### ISSUE TITLE
Are these results tested in a Simulated environemnt or in real-field scenarios ?

### ISSUE THREAD

**Issue by shrin18** [GulatiAditya/DynamicMultiChannelRL#1]
We at KTH Royal Instutute of Technology just presented a presentation on the topic of 

> Deep Learning in Wireless Networks available on this link
`https://docs.google.com/presentation/d/1yahbGKAAo6OfiD_X1meIqbRgo-XdvwOoqOV72CiBi20/edit?usp=sharing`

We were discussing on the implementation of these results in real-life scenarios. Do you think that this has been done ?

**Comment by GulatiAditya** [comment]
Sorry for a late reply, yes these results are on a real-field scenarios. If you see in dataset/real-datatrace it contains an open data of channel scenarios which was captured using TelosB nodes , where two motes were seperated from each other at a distance of 20m. More details of these testbed are in the paper.
